sudo: false

language: python

python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

install:
  - pip install -U pip wheel setuptools
  - pip install tox tox-travis
  - pip install coverage==4.0.3 py pytest pytest-cov python-coveralls
  
script: tox
